### ISSUE TITLE
Support passing repositories to test

### ISSUE THREAD

**Issue by jfontan** [src-d/regression-borges#1]
The list of repositories to test is hardcoded. There should be a way to specify them.

**Comment by erizocosmico** [comment]
Can't assign myself here

**Comment by jfontan** [comment]
The issue did not explain correctly what it meant for custom repositories, sorry. :sweat:

In `regression-core` there is a hardcoded list of repositories to download and use to test borges:

https://github.com/src-d/regression-core/blob/master/repositories.go#L19-L56

The idea is to be able to pass a text file with the repos to test instead of the hardcoded ones. I should have assigned it to me as I had already the loader done.

I've just added data retrieval team as admin.
