### ISSUE TITLE
Download all references from repos

### ISSUE THREAD

**Issue by jfontan** [src-d/regression-borges#2]
The initial repository clone is done with git and downloads the default references. It needs to download the same references that borges does.

**Comment by jfontan** [comment]
Implemented in src-d/regression-core@453412c45f707b39eed871c74843f326f476c7ff. It still needs to update the repo.

**Comment by erizocosmico** [comment]
@jfontan what do you mean it needs "to update the repo"?

**Comment by jfontan** [comment]
It means that it is fixed in `regression-core` but it needs to be updated in `regression-borges` to be available. This last PR does that.
